#ifndef TEAWIN32_H
#define TEAWIN32_H

#include <windows.h>

#define TEAWIN32_WINDOW_CLASS_IDENTIFIER L"_TEAWIN32_"
#define TEAWIN32_WINDOW_CLASS_IDENTIFIER_LENGTH 10

extern DWORD TEAWIN32_INSTANCE_PID;
extern HINSTANCE TEAWIN32_MAIN_INSTANCE;
extern WNDPROC TEAWIN32_WNDPROC;

wchar_t *CreateTEAWin32WindowClassName(LPCWSTR userClass);

#endif
