- arguments: [-XQuasiQuotes]

- group: {name: future, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}

- ignore: {name: Use camelCase}
- ignore: {name: Use >=>}
- ignore: {name: Redundant <&>}

- warn: {name: Redundant do}
