{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -Wno-orphans #-}
{-# OPTIONS_GHC -Wno-missing-export-lists #-}

module TEAWin32.Internal.Foreign where

import           Data.Int       (Int32)
import           Foreign        (Ptr, Storable (..), Word16, Word32, fillBytes,
                                 intPtrToPtr)
import qualified Graphics.Win32 as Win32

foreign import ccall "SetClassLongPtrW"
    c_SetClassLongPtr :: Win32.HWND -> Int32 -> Ptr () -> IO (Ptr ())

foreign import ccall "SetWindowPos"
    c_SetWindowPos :: Win32.HWND -> Win32.HWND -> Int32 -> Int32 -> Int32 -> Int32 -> Win32.UINT -> IO Win32.BOOL

foreign import ccall "DeleteObject"
    c_DeleteObject :: Ptr () -> IO Win32.BOOL

foreign import ccall "ReleaseActCtx"
    c_ReleaseActCtx :: Win32.HANDLE -> IO ()

foreign import ccall "GetSysColorBrush"
    c_GetSysColorBrush :: Word32 -> IO Win32.HBRUSH

foreign import ccall "SelectObject"
    c_SelectObject :: Win32.HDC -> Win32.HANDLE -> IO Win32.HANDLE

foreign import ccall "DrawIconEx"
    c_DrawIconEx :: Win32.HDC -> Int -> Int -> Win32.HICON -> Int -> Int -> Win32.UINT -> Win32.HBRUSH -> Win32.UINT -> IO Win32.BOOL

makeIntResource :: Int -> Win32.LPCTSTR
makeIntResource = intPtrToPtr . fromIntegral

gCLP_HICON :: Int32
gCLP_HICON = -14

gCLP_HCURSOR :: Int32
gCLP_HCURSOR = -12

dEFAULT_GUI_FONT :: Word16
dEFAULT_GUI_FONT = 17

wM_DPICHANGED :: Win32.WindowMessage
wM_DPICHANGED = 0x02E0

mB_CANCELTRYIGNORE :: Win32.MBStyle
mB_CANCELTRYIGNORE = 0x00000006

mB_ICONWARNING :: Win32.MBStyle
mB_ICONWARNING = 0x00000030

mB_ICONERROR :: Win32.MBStyle
mB_ICONERROR = 0x00000010

mB_RIGHT :: Win32.MBStyle
mB_RIGHT = 0x00080000

mB_TOPMOST :: Win32.MBStyle
mB_TOPMOST = 0x00040000

iDCONTINUE :: Win32.MBStatus
iDCONTINUE = 11

iDTRYAGAIN :: Win32.MBStatus
iDTRYAGAIN = 10

type SHSTOCKICONID = Word32

sIID_DOCNOASSOC :: SHSTOCKICONID
sIID_DOCNOASSOC = 0

sIID_DOCASSOC :: SHSTOCKICONID
sIID_DOCASSOC = 1

sIID_APPLICATION :: SHSTOCKICONID
sIID_APPLICATION = 2

sIID_FOLDER :: SHSTOCKICONID
sIID_FOLDER = 3

sIID_FOLDEROPEN :: SHSTOCKICONID
sIID_FOLDEROPEN = 4

sIID_DRIVE525 :: SHSTOCKICONID
sIID_DRIVE525 = 5

sIID_DRIVE35 :: SHSTOCKICONID
sIID_DRIVE35 = 6

sIID_DRIVEREMOVE :: SHSTOCKICONID
sIID_DRIVEREMOVE = 7

sIID_DRIVEFIXED :: SHSTOCKICONID
sIID_DRIVEFIXED = 8

sIID_DRIVENET :: SHSTOCKICONID
sIID_DRIVENET = 9

sIID_DRIVENETDISABLED :: SHSTOCKICONID
sIID_DRIVENETDISABLED = 10

sIID_DRIVECD :: SHSTOCKICONID
sIID_DRIVECD = 11

sIID_DRIVERAM :: SHSTOCKICONID
sIID_DRIVERAM = 12

sIID_WORLD :: SHSTOCKICONID
sIID_WORLD = 13

sIID_SERVER :: SHSTOCKICONID
sIID_SERVER = 15

sIID_PRINTER :: SHSTOCKICONID
sIID_PRINTER = 16

sIID_MYNETWORK :: SHSTOCKICONID
sIID_MYNETWORK = 17

sIID_FIND :: SHSTOCKICONID
sIID_FIND = 22

sIID_HELP :: SHSTOCKICONID
sIID_HELP = 23

sIID_SHARE :: SHSTOCKICONID
sIID_SHARE = 28

sIID_LINK :: SHSTOCKICONID
sIID_LINK = 29

sIID_SLOWFILE :: SHSTOCKICONID
sIID_SLOWFILE = 30

sIID_RECYCLER :: SHSTOCKICONID
sIID_RECYCLER = 31

sIID_RECYCLERFULL :: SHSTOCKICONID
sIID_RECYCLERFULL = 32

sIID_MEDIACDAUDIO :: SHSTOCKICONID
sIID_MEDIACDAUDIO = 40

sIID_LOCK :: SHSTOCKICONID
sIID_LOCK = 47

sIID_AUTOLIST :: SHSTOCKICONID
sIID_AUTOLIST = 49

sIID_PRINTERNET :: SHSTOCKICONID
sIID_PRINTERNET = 50

sIID_SERVERSHARE :: SHSTOCKICONID
sIID_SERVERSHARE = 51

sIID_PRINTERFAX :: SHSTOCKICONID
sIID_PRINTERFAX = 52

sIID_PRINTERFAXNET :: SHSTOCKICONID
sIID_PRINTERFAXNET = 53

sIID_PRINTERFILE :: SHSTOCKICONID
sIID_PRINTERFILE = 54

sIID_STACK :: SHSTOCKICONID
sIID_STACK = 55

sIID_MEDIASVCD :: SHSTOCKICONID
sIID_MEDIASVCD = 56

sIID_STUFFEDFOLDER :: SHSTOCKICONID
sIID_STUFFEDFOLDER = 57

sIID_DRIVEUNKNOWN :: SHSTOCKICONID
sIID_DRIVEUNKNOWN = 58

sIID_DRIVEDVD :: SHSTOCKICONID
sIID_DRIVEDVD = 59

sIID_MEDIADVD :: SHSTOCKICONID
sIID_MEDIADVD = 60

sIID_MEDIADVDRAM :: SHSTOCKICONID
sIID_MEDIADVDRAM = 61

sIID_MEDIADVDRW :: SHSTOCKICONID
sIID_MEDIADVDRW = 62

sIID_MEDIADVDR :: SHSTOCKICONID
sIID_MEDIADVDR = 63

sIID_MEDIADVDROM :: SHSTOCKICONID
sIID_MEDIADVDROM = 64

sIID_MEDIACDAUDIOPLUS :: SHSTOCKICONID
sIID_MEDIACDAUDIOPLUS = 65

sIID_MEDIACDRW :: SHSTOCKICONID
sIID_MEDIACDRW = 66

sIID_MEDIACDR :: SHSTOCKICONID
sIID_MEDIACDR = 67

sIID_MEDIACDBURN :: SHSTOCKICONID
sIID_MEDIACDBURN = 68

sIID_MEDIABLANKCD :: SHSTOCKICONID
sIID_MEDIABLANKCD = 69

sIID_MEDIACDROM :: SHSTOCKICONID
sIID_MEDIACDROM = 70

sIID_AUDIOFILES :: SHSTOCKICONID
sIID_AUDIOFILES = 71

sIID_IMAGEFILES :: SHSTOCKICONID
sIID_IMAGEFILES = 72

sIID_VIDEOFILES :: SHSTOCKICONID
sIID_VIDEOFILES = 73

sIID_MIXEDFILES :: SHSTOCKICONID
sIID_MIXEDFILES = 74

sIID_FOLDERBACK :: SHSTOCKICONID
sIID_FOLDERBACK = 75

sIID_FOLDERFRONT :: SHSTOCKICONID
sIID_FOLDERFRONT = 76

sIID_SHIELD :: SHSTOCKICONID
sIID_SHIELD = 77

sIID_WARNING :: SHSTOCKICONID
sIID_WARNING = 78

sIID_INFO :: SHSTOCKICONID
sIID_INFO = 79

sIID_ERROR :: SHSTOCKICONID
sIID_ERROR = 80

sIID_KEY :: SHSTOCKICONID
sIID_KEY = 81

sIID_SOFTWARE :: SHSTOCKICONID
sIID_SOFTWARE = 82

sIID_RENAME :: SHSTOCKICONID
sIID_RENAME = 83

sIID_DELETE :: SHSTOCKICONID
sIID_DELETE = 84

sIID_MEDIAAUDIODVD :: SHSTOCKICONID
sIID_MEDIAAUDIODVD = 85

sIID_MEDIAMOVIEDVD :: SHSTOCKICONID
sIID_MEDIAMOVIEDVD = 86

sIID_MEDIAENHANCEDCD :: SHSTOCKICONID
sIID_MEDIAENHANCEDCD = 87

sIID_MEDIAENHANCEDDVD :: SHSTOCKICONID
sIID_MEDIAENHANCEDDVD = 88

sIID_MEDIAHDDVD :: SHSTOCKICONID
sIID_MEDIAHDDVD = 89

sIID_MEDIABLURAY :: SHSTOCKICONID
sIID_MEDIABLURAY = 90

sIID_MEDIAVCD :: SHSTOCKICONID
sIID_MEDIAVCD = 91

sIID_MEDIADVDPLUSR :: SHSTOCKICONID
sIID_MEDIADVDPLUSR = 92

sIID_MEDIADVDPLUSRW :: SHSTOCKICONID
sIID_MEDIADVDPLUSRW = 93

sIID_DESKTOPPC :: SHSTOCKICONID
sIID_DESKTOPPC = 94

sIID_MOBILEPC :: SHSTOCKICONID
sIID_MOBILEPC = 95

sIID_USERS :: SHSTOCKICONID
sIID_USERS = 96

sIID_MEDIASMARTMEDIA :: SHSTOCKICONID
sIID_MEDIASMARTMEDIA = 97

sIID_MEDIACOMPACTFLASH :: SHSTOCKICONID
sIID_MEDIACOMPACTFLASH = 98

sIID_DEVICECELLPHONE :: SHSTOCKICONID
sIID_DEVICECELLPHONE = 99

sIID_DEVICECAMERA :: SHSTOCKICONID
sIID_DEVICECAMERA = 100

sIID_DEVICEVIDEOCAMERA :: SHSTOCKICONID
sIID_DEVICEVIDEOCAMERA = 101

sIID_DEVICEAUDIOPLAYER :: SHSTOCKICONID
sIID_DEVICEAUDIOPLAYER = 102

sIID_NETWORKCONNECT :: SHSTOCKICONID
sIID_NETWORKCONNECT = 103

sIID_INTERNET :: SHSTOCKICONID
sIID_INTERNET = 104

sIID_ZIPFILE :: SHSTOCKICONID
sIID_ZIPFILE = 105

sIID_SETTINGS :: SHSTOCKICONID
sIID_SETTINGS = 106

sIID_DRIVEHDDVD :: SHSTOCKICONID
sIID_DRIVEHDDVD = 132

sIID_DRIVEBD :: SHSTOCKICONID
sIID_DRIVEBD = 133

sIID_MEDIAHDDVDROM :: SHSTOCKICONID
sIID_MEDIAHDDVDROM = 134

sIID_MEDIAHDDVDR :: SHSTOCKICONID
sIID_MEDIAHDDVDR = 135

sIID_MEDIAHDDVDRAM :: SHSTOCKICONID
sIID_MEDIAHDDVDRAM = 136

sIID_MEDIABDROM :: SHSTOCKICONID
sIID_MEDIABDROM = 137

sIID_MEDIABDR :: SHSTOCKICONID
sIID_MEDIABDR = 138

sIID_MEDIABDRE :: SHSTOCKICONID
sIID_MEDIABDRE = 139

sIID_CLUSTEREDDRIVE :: SHSTOCKICONID
sIID_CLUSTEREDDRIVE = 140

instance Storable Win32.RECT where
    sizeOf _ = sizeOf (0 :: Win32.LONG) * 4

    alignment _ = alignment (0 :: Win32.LONG)

    peek ptr = do
        left   <- peekByteOff ptr 0
        top    <- peekByteOff ptr (sizeOf (0 :: Win32.LONG))
        right  <- peekByteOff ptr (sizeOf (0 :: Win32.LONG) * 2)
        bottom <- peekByteOff ptr (sizeOf (0 :: Win32.LONG) * 3)

        pure (left, top, right, bottom)

    poke ptr (left, top, right, bottom) = do
        fillBytes ptr 0 (sizeOf (0 :: Win32.LONG) * 4)

        pokeByteOff ptr 0 left
        pokeByteOff ptr (sizeOf (0 :: Win32.LONG)) top
        pokeByteOff ptr (sizeOf (0 :: Win32.LONG) * 2) right
        pokeByteOff ptr (sizeOf (0 :: Win32.LONG) * 3) bottom
